### PR TITLE
iOS 18 ScrollView Introspect

### LINKED ISSUE #1121: [iPadOS] Backdrop z-index too high
## Description:

Backdrops have z-axis hierarchy where it shouldn't, clipping over other UI elements when viewing item details. Screen recording attached below.

## To reproduce:

1. Open any item
2. Swipe up

## Screen Recording:

https://github.com/jellyfin/Swiftfin/assets/13402525/bc944314-7960-4cbf-a644-e07b0005bf49

### Application version

1.1

### Where did you install the app from?

App Store

### Device information

iPad Air 13-inch (M2, 2024)

### OS version

iPadOS 18.0 (22A5282m)

### Jellyfin server version

10.9.6

### PR DESCRIPTION
**Pull request by LePips**
Fixes #1121

### CODE REVIEW

**Review by PangMo5 — APPROVED** [review]

File: Shared/Extensions/ViewExtensions/Modifiers/ScrollViewOffsetModifier.swift [hunk 1]
```diff
@@ -19,7 +19,17 @@ struct ScrollViewOffsetModifier: ViewModifier {
...
 
     func body(content: Content) -> some View {
-        content.introspect(.scrollView, on: .iOS(.v15), .iOS(.v16), .iOS(.v17), .tvOS(.v15), .tvOS(.v16), .tvOS(.v17)) { scrollView in
+        content.introspect(
+            .scrollView,
+            on: .iOS(.v15),
+            .iOS(.v16),
+            .iOS(.v17),
+            .iOS(.v18),
+            .tvOS(.v15),
```
Comment (holow29) [inline Shared/Extensions/ViewExtensions/Modifiers/ScrollViewOffsetModifier.swift:28]: Since tvOS 17 is now minimum, should probably remove the references to earlier versions.

**Comment by LePips** [comment]
Yes, I timed this poorly. This will be out soon.
