### PR TITLE
`BaseItemDto` Editing Cleanup

### LINKED ISSUE #1869: Unable to edit item metadata
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our [forum or chat rooms](https://jellyfin.org/contact/) first to troubleshoot with volunteers, before creating a report.
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/Swiftfin/issues?q=is%3Aopen+is%3Aissue).
- [x] I'm using an up to date version of Swiftfin; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).

### Description of the bug

Get 500 error when attempting to edit metadata of an item.

### Reproduction steps

- Edit any metadata property of an item
- Hit `Save`
- See 500 error in Swiftfin logs, see serialization error in server logs

### Platform

iOS

### Application version

main

### Where did you install the app from?

None

### Device information

all

### OS version

all

### Jellyfin server version

10.11.5

### Screenshots or videos

_No response_

### Relevant log output

```shell
[2025-12-20 14:28:01.686 -07:00] [ERR] [24] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Items/038e4407b5819482a6cf0670a2449ec0".
System.InvalidOperationException: Each parameter in the deserialization constructor on type 'MediaBrowser.Model.Dto.TrickplayInfoDto' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, T& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### PR DESCRIPTION
**Pull request by JPKribs**
## Summary

Resolves: https://github.com/jellyfin/Swiftfin/issues/1869

While trying to resolve #1869, I wanted to convert over the `ItemEditorViewModel` and it's extensions to use the new `@Stateful` macros. This led me to the views themselves which I created about a year ago. With what I know now, there is some room for improvement. The primary changes made:

1. Move all Item Permissions from the `UserSession` to the `BaseItemDto`. The current usage of this was pretty bulky and required getting the permissions from a separate location using the item as an input. Instead, this just puts the permissions directly on the `BaseItemDto` since that's the only place where these can be used anyway.
2. Hide the `PlayButton` if the user does not have permission to play content from Jellyfin. I don't imagine this comes up often. I am only aware of this because I have an admin account that doesn't have playback permission and this button throws a non-descriptive error from the server. Hiding the button seems like the cleaner solution.
3. Unified `ItemEditorMenu` struct. The menu dropdown items are the same between iOS and tvOS (kind of) so this lets us keep all the permission logic and routing in a single spot for later.
4. A more detailed `ItemDeletionView`. Especially for Series, it can be hard to determine what specifically you are deleting. This gives the full count of items deleted, and the type/details. This should help prevent any heartache where someone thinks they are deleting an episode but delete a series.
5. For the `EditItemElementViewModels`s, I've changef this from using a trie to instead just do a search and debounce. This is more performant for items where searching is available. Tags cannot do this so that will still use the trie.
6. `EditItemElementView`s, was broken where I could re-add the same genre, tag, studio, or person unlimited times. This blocks adding duplicates to the same item now.
7. Moved `AdminDashboardView/Components/MediaItemSection.swift` -> `/Components/ItemFormSection.swift` since this is used outside of the `AdminDashboard` now. It's a good way to display `BaseItemDto` in a form so this helps with re-use.
8. Removed the progress on `RefreshMetadataViewModel` since we don't have the progress anymore. Eventually, most of this will be deleted since the websocket will be able to get the refreshed item instead of use counting to 5 and manually refreshing.
9. The ConnecToServerView -> ConnectToServerView typo fix.
10. Instead of doing many permission checks throughout the `ItemEditorView` I'm just purely leaving that as admin edit actions and moving subtitles (non-admin) and refresh Metadata functionality to the dropdown. It makes the permissions a bit easier to handle and centralizes the tvOS and iOS permission checks.
11. Added a dummy `navigationBarCloseButton` for tvOS. We can make one here but I don't see a benefit since the natural interaction is the back button.
12. Cleanup in the same fashion for `AddServerUserAccessTagsView` since we are doing tag searches with the same ViewModel there so that should reflect the Metadata editing

## TODOs

- I wanted to move the `DeleteItemViewModel` over to use the new `@Stateful` macros but I think this `ViewModel` should just get rolled into either `ItemEditorViewModel` or `ItemViewModel` instead. I held off until after https://github.com/jellyfin/Swiftfin/pull/1752 if that is the best route. I just feel as though a whole `ViewModel` for a single deletion function is overkill.

## Videos

Please note these only return a 404 because the test file I am using doesn't exist. I added the entry manually so there is no actual file to delete hence 404

### tvOS

https://github.com/user-attachments/assets/fe043500-c467-414c-87ad-6d9cff724088

### iOS

https://github.com/user-attachments/assets/3feb676d-a941-41dc-b540-9e4ef8433620

## Image

<details>

<summary>iOS Episode</summary>

Simulator Screenshot - iPhone - 2025-12-21 at 01 01 10

</details>

<details>

<summary>tvOS Series</summary>

Simulator Screenshot - Apple TV - 2025-12-21 at 00 50 46

</details>

### CODE REVIEW

**Comment by JPKribs** [comment]
This is a weird one. It's all kind of interconnected. There are some smaller ones I could break out like moving permissions over to the `BaseItemDto` but that's a fairly small part of this. Most of this work is the migration of the `ItemEditorViewModel` to `@Stateful` but there is 4x the work since we have 4x extensions on this that all need the same changes.

If there's anything we'd rather split out let me know. The goal was originally to fix https://github.com/jellyfin/Swiftfin/issues/1869 but I kept finding things that needed clean up.

The only part of this I'm not 100% confident in is the [ItemEditorMenu](https://github.com/jellyfin/Swiftfin/blob/25de44ddb604bad3a451b131fc695eb543893f28/Shared/Views/ItemView/Components/ItemEditorMenu.swift). I like that it centralizes all of our editing logic and permission checks into 1 spot for both iOS and tvOS. It's much much cleaner BUT I don't know if making a struct for Menu Contents is good swift programming.

File: Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+Permissions.swift [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+//
+
+import Factory
+import JellyfinAPI
+import SwiftUI
+
+extension BaseItemDto {
+
+    /// Indicates whether the item can be downloaded by the current user
+    var canBeDownloaded: Bool {
```
Comment (LePips) [inline Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+Permissions.swift:16]: I leave this here for when we implement downloads and may have an additional local setting, but it isn't necessary to check the policy for content downloading permissions as the server will already tag that on `canDownload` for the user that retrieved the item.

**Review by LePips — APPROVED** [review]
Good work! I do leave some todos for some next steps of this work.

File: Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+Permissions.swift (hunk 1 above)
Comment (JPKribs) [reply Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+Permissions.swift:16]: Agreed. I think this is just scaffolding for now. I was briefly looking at a "File Size v Available Storage" check but that's likely in the download manager instead. I'm almost certain we will have some settings around this but I can't tell you specifically what those will be haha
