### PR TITLE
Fix Seasons Sorting

### LINKED ISSUE #383: Number seasons in numerical order
**Describe the feature you'd like**
Can we get seasons numbered in numerical order, and not by the starting digit?

How it is:
image

**Additional context**
Seasons are categorized by their starting digit, instead of the logical way which is 1-9,10-19, etc.

### PR DESCRIPTION
**Pull request by LePips**
Fixes seasons sorting for the small menu, small fix that we weren't able to catch because CI is off rn, and a linting fix I said that I would fix.

Closes #383

### CODE REVIEW

**Comment by LePips** [comment]
@jhays this probably breaks the Livetv channel cards because they are no longer focusable. I honestly didn't notice that these views were in Shared, they should eventually be moved to the tvOS project and that focus modifier added back in.

**Review by PangMo5 — APPROVED** [review]

File: Swiftfin/Components/EpisodesRowView/EpisodesRowView.swift [hunk 1]
```diff
@@ -29,7 +29,8 @@ struct EpisodesRowView<RowManager>: View where RowManager: EpisodesRowManager {
 					}
 				} else {
 					Menu {
-						ForEach(Array(viewModel.seasonsEpisodes.keys).sorted(by: { $0.name ?? "" < $1.name ?? "" }), id: \.self) { season in
+						ForEach(Array(viewModel.seasonsEpisodes.keys).sorted(by: { $0.indexNumber ?? 0 < $1.indexNumber ?? 0 }),
```
Comment (PangMo5) [inline Swiftfin/Components/EpisodesRowView/EpisodesRowView.swift:32]: It may be better to implement a `Comparable` protocol or to be in charge of logic in ViewModel.

Comment (LePips) [reply Swiftfin/Components/EpisodesRowView/EpisodesRowView.swift:32]: You're right, good catch. I'll do that now instead

**Review by PangMo5 — APPROVED** [review]
