### PR TITLE
[tvOS][QOL] Supports back button click when in the native player.

### LINKED ISSUE #925: [ATV] Cannot exit playing session with native player
### Describe the bug

1. Login/setup Swiftfin \w Jellyfin server
2. Go to settings, toggle "player" to "native"
3. Go to any media, play
4. Press "return", see that it doesn't work, except the main-menu long-press return

### Application version

Latest main, eb17300061315ff310749871f5b79032385ba55a

### Where did you install the app from?

None

### Device information

Apple TV HD

### OS version

tvOS 17.1

### Jellyfin server version

10.8.12

### PR DESCRIPTION
**Pull request by nokeeo**
Conforms `UINativeVideoPlayerViewController` to `AVPlayerViewControllerDelegate` and implements `playerViewControllerShouldDismiss`.  This method is called by AV player view controller when the player should be dismissed.  This function is only called when the playback overlay is not displayed otherwise a back button press will dismiss the overlay.

Fixes #925

### CODE REVIEW

**Comment by nokeeo** [comment]
ping @LePips for review or please assign to whomever is appropriate.

File: Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift [hunk 1]
```diff
@@ -57,7 +56,9 @@ struct NativeVideoPlayerView: UIViewControllerRepresentable {
     func updateUIViewController(_ uiViewController: UINativeVideoPlayerViewController, context: Context) {}
 }
 
-class UINativeVideoPlayerViewController: AVPlayerViewController {
+// TODO: Refactor such that this does not subclass AVPlayerViewController. Subclassing is not
+// supported according to the apple docs.
+class UINativeVideoPlayerViewController: AVPlayerViewController, AVPlayerViewControllerDelegate {
```
Comment (LePips) [inline Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift:61]: Thank you for your contribution, however this isn't correct. We don't need to subclass from anything for this to work. In `VideoPlayerCoordinator` we create the view like so:

```swift
PreferenceUIHostingControllerView {
    Group {
        if Defaults[.VideoPlayer.videoPlayerType] == .swiftfin {
            VideoPlayer(manager: self.videoPlayerManager)
        } else {
            NativeVideoPlayer(manager: self.videoPlayerManager)
        }
    }
}
.ignoresSafeArea()
```

where the tvOS implementation of `PreferenceUIHostingControllerView` is a view that overrides button presses that we can detect in the Swiftfin video player. As we see above, the native player is wrapped in this view but we don't want it to be. This should be changed to the following, where the native player can handle all of its own button presses:

```swift
if Defaults[.VideoPlayer.videoPlayerType] == .swiftfin {
    PreferenceUIHostingControllerView {
        VideoPlayer(manager: self.videoPlayerManager)
    }
    .ignoresSafeArea()
} else {
    NativeVideoPlayer(manager: self.videoPlayerManager)
}
```

Luckily I was going to work on PRs and other work today, but please don't ping me in the future for reviews. I do see everything, but only get to stuff when I can.

**Review by LePips — CHANGES_REQUESTED** [review]

File: Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift (hunk 1 above)
Comment (nokeeo) [reply Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift]: >  please don't ping me in the future for reviews

Apologies.  It wasn't clear how to get a review and noticed that in an accepted PR someone pinged a maintainer.  Won't do in the future.

Incorporated these suggestions.  PTAL.

File: Shared/Coordinators/VideoPlayerCoordinator.swift [hunk 2]
```diff
@@ -45,19 +45,17 @@ final class VideoPlayerCoordinator: NavigationCoordinatable {
             AppDelegate.enterPlaybackOrientation()
         }
 
-        #else
-
-        PreferenceUIHostingControllerView {
-            Group {
-                if Defaults[.VideoPlayer.videoPlayerType] == .swiftfin {
+        #else // os(iOS)
```
Comment (LePips) [inline Shared/Coordinators/VideoPlayerCoordinator.swift:48]: Don't need these comments

File: Shared/Coordinators/VideoPlayerCoordinator.swift [hunk 3]
```diff
@@ -45,19 +45,17 @@ final class VideoPlayerCoordinator: NavigationCoordinatable {
...
                 }
             }
+            .ignoresSafeArea()
+        } else {
+            NativeVideoPlayer(manager: self.videoPlayerManager)
         }
-        .ignoresSafeArea()
-
-        #endif
+        #endif // os(iOS)
```
Comment (LePips) [inline Shared/Coordinators/VideoPlayerCoordinator.swift:59]: and here

File: Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift [hunk 4]
```diff
@@ -37,7 +37,6 @@ struct NativeVideoPlayer: View {
             if let _ = videoPlayerManager.currentViewModel {
                 playerView
             } else {
-//                VideoPlayer.LoadingView()
```
Comment (LePips) [inline Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift:40]: Actually leave this, this is just left over from forever ago for when this needs to be properly implemented.

**Review by LePips — CHANGES_REQUESTED** [review]
Just some cleanup, good to have the refactor comment about subclassing from `AVPlayerViewController`. Yeah it says subclassing isn't supported but we can generally get away/lazy with it, but we should wrap that into a parent view/VC that interacts with the underlying `AVPlayerViewController`.

File: Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift (hunk 4 above)
Comment (nokeeo) [reply Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift:40]: Added a TODO instead of leaving commented out code to make the intention a little bit more explicit.

File: Shared/Coordinators/VideoPlayerCoordinator.swift (hunk 2 above)
Comment (nokeeo) [reply Shared/Coordinators/VideoPlayerCoordinator.swift]: I personally like this style as I find it makes it easier to visually parse preprocessor expressions especially if they are nested, but reverted this change.

File: Shared/Coordinators/VideoPlayerCoordinator.swift [hunk 5]
```diff
@@ -46,18 +46,16 @@ final class VideoPlayerCoordinator: NavigationCoordinatable {
         }
 
         #else
-
-        PreferenceUIHostingControllerView {
-            Group {
-                if Defaults[.VideoPlayer.videoPlayerType] == .swiftfin {
+        if Defaults[.VideoPlayer.videoPlayerType] == .swiftfin {
+            PreferenceUIHostingControllerView {
+                Group {
```
Comment (LePips) [inline Shared/Coordinators/VideoPlayerCoordinator.swift:51]: Since you have to lint anyways, this `Group` can be removed.

File: Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift [hunk 6]
```diff
@@ -37,7 +37,7 @@ struct NativeVideoPlayer: View {
...
+                // TODO: Implement more polished loading screen.
```
Comment (LePips) [inline Swiftfin tvOS/Views/VideoPlayer/NativeVideoPlayer.swift:40]: To me, the commented out view is better because that's the actual view that needs to be implemented. (see the file/view)

**Review by LePips — CHANGES_REQUESTED** [review]

**Comment by nokeeo** [comment]
Done.  PTAL.

**Review by LePips — APPROVED** [review]
