### PR TITLE
Navigation and Item Overhaul

### LINKED ISSUE #336: List Video and Audio tags in video overview
When looking at a video, it should be obvious what the resolution and color options are for the video.  Things like 4k, HD, HDR, Dolby Vision, etc.

Here's a screenshot of the current view:
image

Here's a screenshot of the same video in Infuse that shows the video tags:
image

It would also be great to see audio tags such as Dolby Atmos, or 5.1, etc.

Another example of an app showing audio tags:
image

### LINKED ISSUE #345: Media views with Logo ?
1 / Is it possible to insert media logos in the media view ?
 .
Insert them in such a way that they only appear in the media page because when the logos appear in the main page, it's too busy.

Capture d’écran 2022-01-23 à 14 12 43

I tried for the fanart seasons but couldn't separate them, what I put for the media view also appears
in the recommendations on the home page.

Is it possible to use the Jellyfin logo only on the media page?

Capture d’écran 2022-01-23 à 14 11 27

2/ Will there be an option to use landscape posters, thumbnails, which I think is the more modern format for views instead of classic posters.
Many applications like infuse, plex, Squire, use this classic cover format.

As Swiftfin is intended as a native application to tvOS,

Why not ?

### LINKED ISSUE #373: favorate icon can't autoupdate.
### Describe the bug

favorites icon cannot auto update.
liked or unliked a movie，the icon remains the previous stutus. need manual refresh to update the favorite  icon.

### Application version

69 & 71

### Where did you install the app from?

_No response_

### Device information

iphone 12 mini

### OS version

15.3

### Jellyfin server version

10.7.7

### LINKED ISSUE #418: Long names make the whole UI shift off screen
### Describe the bug

When a show has a version name that is extremely long, instead of truncating it, the whole UI is shifted left, making many buttons inaccessible.

### Current Behaviour

IMG_0102

### Expected Behaviour
IMG_0103

### Steps to reproduce
1. Have multiple versions of an episode of a show, with long file names.
2. Group them into a single group within the Jellyfin web interface. (See https://features.jellyfin.org/posts/251/multiple-versions-drop-down-on-tv-series)
3. Access the title via Swiftfin.

### Application version

1.0.0(74)

### Where did you install the app from?

TestFlight

### Device information

iPad (6th Generation) A1893

### OS version

iPadOS 15.4.1

### Jellyfin server version

10.7.7

### LINKED ISSUE #443: Low number of up next/continue watching
It seems up next is limited to 6 items. It'd be awesome if that number were increased to something like 40. An option to have up next and continue watching would also be awesome

### LINKED ISSUE #488: Do not navigate to the same episode when the current route is the same episode
**Describe the feature you'd like**
When I see the page for a show's seasson, there's this vertical list of episodes. You can tap one and you are taken to the detail. If you tap the same episode again, you navigate to the same episode detail. You can keep doing this and the navigation will happen.
At the end you would have to hit back several times to return home.

Could you check the current route and if the current route (for episode, movie, etc.) is the same as the one you are about to navigate, cancel the navigation?

**Additional context**

### LINKED ISSUE #489: Series Items are clipped when focussed in tvOS
### Describe the bug

1. Go to a series
2. Select a season

Expected: Season is scaled to a size of `1.1` with all content fully visible
Actual: Content is clipped so that you cannot see number of unplayed episodes or the season and year text properly

clipped

### Application version

1.0.0 (75)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K

### OS version

tvOS 15.4

### Jellyfin server version

10.8.1

### PR DESCRIPTION
**Pull request by LePips**
For anybody who wants to actually look at the code, check out the changes locally and good luck.

# Background

This PR aimed to address the issue of episode navigation and make items "more like the Apple TV app" from [this discussion](https://github.com/jellyfin/Swiftfin/discussions/431). I got most of the way there in this PR. Stopped short out of sanity and will continue over time. Further developments are listed at the end of this summary.

For context, "items" refer to movies, series, episodes, and collections.

## iOS Features

There are now **three** options to present items:
<details>
<summary>Compact Poster</summary>
<br>

https://user-images.githubusercontent.com/20747774/182678633-a3ba7af1-eacd-4fd8-91b4-948c6799a5d6.mp4
</details>

<details>
<summary>Compact Logo</summary>
<br>

https://user-images.githubusercontent.com/20747774/182678785-5c1e4d6f-de2b-4ecb-9a33-5659f0a508a8.mp4
</details>

The above views use a feature of the BlurHash to get the average linear RGB color value and create a gradient to "extend" the image, similar to [how Apple does it](https://is1-ssl.mzstatic.com/image/thumb/hsZY3UtokkE2RYd896JRlQ/1680x3636.jpg). It's not perfect since it's literally just the _average_ RGB value and while there is an alternate [bottom edge color](https://github.com/woltapp/blurhash/blob/1f7afa0db25f26aee8a9bdb64af5e00f8b3a79d1/Swift/BlurHashKit/ColourProbes.swift#L51) from the BlurHash, I found the average to work marginally better. I have raised the idea of providing the dominant, prominent, and other colors from images among the JF devs so it may happen and look a lot better in the future. I would use these colors to create gradients and make a lot of improvements with these item views and other places images are used.

<details>
<summary>Cinematic</summary>
<br>

https://user-images.githubusercontent.com/20747774/182678897-91fd0344-8b32-4a2e-9c1a-9375d221e71f.mp4
</details>

The cinematic view is tricky since both the poster and backdrop are not guaranteed at all to be centered. Additionally, the poster will 99% have text on the image so with the logo it won't look as nice. Regardless, it was just an easy implementation and you will eventually be able to change between the poster or the backdrop.

For a series view, there is a Season and Episode selector. Episodes are a single button that will take you to the episode view to see its details. This frankly does not solve the original issue of episode navigation for now on iOS/iPadOS _but_ this will be redone when I get to landscape vs poster stack customization.

Episodes now have their own view:

<details>
<summary>Episodes</summary>
<br>

https://user-images.githubusercontent.com/20747774/182679070-30071ed3-f13d-4fb6-9395-53d46439e195.mp4
</details>

This view looks different than the other three on iOS only because the content provided by an episode can't fill in the poster or logo.

## iPadOS Features

iPadOS now has a single view shared across all items:

<details>
<summary>Cinematic Movie</summary>
<br>

https://user-images.githubusercontent.com/20747774/182679219-5d9ef104-bde6-4b60-8fb3-92ea4882e45a.mp4
</details>

<details>
<summary>Cinematic Series</summary>
<br>

https://user-images.githubusercontent.com/20747774/182679307-ca54bdb0-b14a-4c17-8036-ea5f4fe13c35.mp4
</details>

<details>
<summary>Cinematic Collection</summary>
<br>

https://user-images.githubusercontent.com/20747774/182679382-b439704a-d5ad-4cb1-97a0-d330155e27db.mp4
</details>

<details>
<summary>Cinematic Episode</summary>
<br>

https://user-images.githubusercontent.com/20747774/182679488-ded6eb0f-2fd6-4083-a0ca-c4cc19db4d4f.mp4
</details>

All items use this view and it looks really nice due to the larger screen and aspect ratio.

## tvOS Features

iPadOS now has a single view shared across all items:

<details>
<summary>Cinematic Movie</summary>
<br>

https://user-images.githubusercontent.com/20747774/182683199-c4a9570a-1ca1-4d3e-a6ef-23eeff758e55.mp4
</details>

<details>
<summary>Cinematic Series and Episode</summary>
<br>

https://user-images.githubusercontent.com/20747774/182683339-b3e47f8f-1414-40bc-8494-f5810cb9fa46.mp4
</details>

For a series view, there is a new Season and Episode selector. When this view is gains focus, it will default to the Seasons row by design as a workaround due to tvOS and the Focus Engine. There are two buttons per episode:
1 - top with the backdrop which will play the episode when selected
2 - bottom with details which will open the episode item when selected

<details>
<summary>Cinematic Collection</summary>
<br>

https://user-images.githubusercontent.com/20747774/182683429-6903f73d-74f0-436e-9db7-83d84151c531.mp4
</details>

This scroll view was very painful to implement because of the lack of tvOS SwiftUI support. This view is kind of fragile, meaning if you try to navigate quickly it will break so please be patient with it.

## Other Features and Feature Notes

 - Views that feature a logo will fallback to text if no logo available
 - More attributes like 4k, 5.1, and 7.1 sound
 - Better series episode auto-selection
 - About view for all items with poster and overview
 - Item tag now with the overview

### iPadOS and tvOS single option
While iOS has three item view options, iPadOS and tvOS only have a single cinematic view. I planned on also doing a compact view as well for iPadOS and tvOS but thought it was unnecessary as the cinematic view looks great on the larger screens and a compact view wouldn't serve much purpose. However, if a good compact view is presented I may consider it.

### Buttons underneath play button
Right now there are only two buttons shown with every view: watched and favorited. If a view has multiple versions, it will also present a third button. It looks quite empty and awkwardly spaced right now _but_ this will be changed in time when the Download and Edit buttons are added as well (iOS and iPadOS). Overall, I think these buttons could have a better design with some kind of material background with a tinted color. Just need to have some kind of background instead of the just the plain icon in most views (probably not in Compact Poster).

# Developer Notes

Frankly, listing all of the features above doesn't make it seem like it was a lot of work... but everything that the item view, and I mean everything, was entirely rewritten and this propagated throughout the rest of the app. To start, I refactored some of the main views, `BaseItemDto` image references, and a lot more I just won't be listing. I learned a lot throughout the evolution of this PR with SwiftUI practices and overall API/object design. This learning caused many refactors over time.

## View Declarations
As you can see, all the views are now separated by their type. This is a huge change from [my old PR](https://github.com/jellyfin/Swiftfin/pull/165) combining all of them. Part of what I've learned over time with good SwiftUI practices is _what_ should be combined or separated. The _base_ of all these views are shared by what scroll view they are implemented in and the _content_ is separated by view. This makes things a lot more declarative for how individual views should look like and separation of concerns for views. I'm being a bit hand-wavy here but by thinking about the view trees in your head you should understand it.

 I also really hated having `if let __ViewModel = viewModel as? __ViewModel`. Looked terrible.

## tvOS
tvOS was a **_PAIN_**. There is a little to no tvOS SwiftUI support and this past WWDC literally brought nothing new. I attempted many times to wrap some of the [TVUIKit](https://developer.apple.com/documentation/tvuikit) views but they literally cannot be wrapped and attempting to make mocks of them in SwiftUI make the app laggy because the `FocusState` redraws views whenever _any_ view gets a new focus. This was prominent in an `HStack` for portrait items where these views would be used anyways.

As mentioned above, the scroll view is very fragile. This is because the Focus Engine on tvOS will scroll to a focused view in a very specific way and I was unable to turn off scrolling with any mechanism. I wrote a custom `FocusGuide` that I thought was _soooooo_ clever but can be a pain to work with because we have to strongly control _what_ is on the screen and _what_ has focus at any time. I also implemented some custom scrolling but even this has issues because of the fading in/out logo/text and when the user has any input during the animation it _cancels_. By playing around with the Apple TV app I think they use a collection view/table view so I may look at that sometime. No matter what, these views need to be entirely redone in the long term.

## Widget Removal
I removed the widget from the project because:
1 - it doesn't work right now, and hasn't for a long time, due to Shared Groups
2 - it was written a long time ago and needs to be redone with our new SwiftUI practices
3 - it had too many errors I didn't bother to fix when I brought over my work from my old branch

I'm being a bit hand-wavy here too but this needed to happen. Trust me. 

### 🧠 dump

- BlurHashKit was copied over from the original BlurHash source. This was to get the colors from the BlurHash and I wish there was a Swift Package of the implementation. A PR has been on the repo for over a year for SPM support but I wouldn't want to use it anyways as it will also grab all of the other implementations. I might just make the package myself with only the Swift implementation.
- `ImageView` was changed a lot and it will change again. The layout of the image and fallback text is incorrect due to how containing views work in SwiftUI and their properties, mainly with sizes and alignments. The following images show the problem:

<details>
<summary>iOS</summary>
<br>

The view below has bottom padding, it should have some but not that much.

ios-text-off

</details>

<details>
<summary>iPadOS and tvOS</summary>
<br>

The views below show the logo/text having a leading or bottom padding. The logo/text should have a bottom leading alignment.

tvos-logo-off
ipados-logo-off
tvos-title-off
</details>

This would just take changing how images are displayed to probably the following:
```swift
ImageView(... image source ...) { image in
    image
        .frame(...)
        .cornerRadius(...)
        .padding()
} failureView: {
    Text(... item title ...)
        .font(...)
}
```

I don't know if this would be an entire refactor or just an additional usage right now. A custom placeholder view would also be added instead of _always_ being a BlurHash, especially for logos because they are just a solid colors and don't look nice so the title should be used instead. Also, sources without a blurhash just display a clear color.
- The `BaseItemDto` now has a more central and dynamic way to get images.
- I will be a bit more picky with how things are named. This comes from changing stuff like `PortraitImageHStackView`, to a few things, to finally `PortraitPosterHStack` as I learned to mirror SwiftUI naming conventions.
- Use `ScaledMetric` to scale views automatically. Right now I manually check for iPadOS/iOS for portrait poster sizing.
- Create `LandscapePosterHStack`, landscape analog of `PortraitPosterHStack`
- Refreshing the home screen was removed in tvOS. A refresh functionality will be re-added as part of the refactoring the `SessionManager` to be in the environment. (`SessionManager` will be changed to a new name too)
- Collections will have their own kind of page. Instead of listing things horizontally it should be a grid and I need to think about what should happen with the play button. Probably to first unwatched in the list and first if all watched.
- I really, really, really need to learn the `UICollectionView` wrappers. I would replace a lot of views with collection views.
- I did _not_ test with any unaired/missing items so these views may not work properly there, I don't know.
- Seasons are not accessible. This was deliberate due to time and I thought were low value because who really looks at seasons anyways? They will be re-added later but really only if somebody requests it.
- The iPadOS and tvOS cinematic views mirror Apple TV a bit with some notable changes. Mainly, the buttons being on the right instead of the left. This was a deliberate design decision due to how I wanted the logo/text on the bottom instead of the top like Apple. This overall created a design that makes us stand out as our own. Not stand out as the "best", but our own.
- I used nested `struct`s and other type declarations to create namespaces with many of the new views. This has become a good practice and will be used more throughout the app.
- The item details (like subtitles/audio/filename) are used in some views and not in others. This needs to be refactored.
- The Series and Episode selector needs to be fixed, most likely refactored, because most times the view loads before the episodes are loaded.
- I applied a gradient mask to blur views to create nice transitions. However none of these transitions are perfect and need to be redone.
- I will most likely be refactoring some other things I wrote in here because I'm that type of person. 😢
- Every time I look at this app, I can see every little thing that needs to happen and keep these notes inside my head. Instead of creating a ton of issues regarding small code changes, I will probably create a Notion page with everything I think about and have that linked to a pinned issue.

Closes #336 
Closes #345 
Closes #373 
Closes #418
Closes #443
Closes #488
Closes #489 

In the end, I did not get to _everything_ I wanted to finish in this PR but as you can tell ... it's gigantic. I just picked up whatever I wanted to work on along the way and left a lot of notes of what needs to change. I kind of just went crazy working on this for so long and need to work on other things in the app to break it up, even with the imperfections and regressions. Thank you and good night.

### CODE REVIEW

**Comment by PangMo5** [comment]
That's awesome! I'll check it out soon when I have time

File: Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift [hunk 1]
```diff
@@ -0,0 +1,165 @@
...
+                    resizingMode: .aspectFit
+                ) {
+                    Text(viewModel.item.displayName)
+                        .font(.largeTitle)
+                        .fontWeight(.semibold)
+                        .lineLimit(2)
+                        .multilineTextAlignment(.leading)
+                        .foregroundColor(.white)
+                }
+                .frame(maxWidth: UIScreen.main.bounds.width * 0.4, maxHeight: 100)
```
Comment (PangMo5) [inline Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift:119]: It looks really cool with the logo, but it looks like there is an alignment problem with the text only.
It seems that it needs to be solved by adjusting the alignment of the frame, not by adjusting the text alignment.
```swift
.frame(maxWidth: UIScreen.main.bounds.width * 0.4, maxHeight: 100, alignment: .leading)
```

There may be a similar problem in other places that you I haven't checked.

Comment (LePips) [reply Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift:119]: Please see the item about the `ImageView` in "🧠 dump". This issue affects both the logo and the text.

Comment (PangMo5) [reply Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift:119]: Oh, I can understand that part now.

Then my opinion on this is

In the `iPadOS CinematicScrollView.OverlayView`, I think that normally work if the modifier only be applied to FailureView.

However, In other situations, it may be necessary to use the modifier of `FailureView`, which is contrary to the modifier of `ImageView`, so it would be good to provide the initializer mentioned in ImageView at the same time.

For implementation in the way you mentioned, it would be good to refer to Nuke's `ImageContainer`.

Comment (PangMo5) [reply Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift:119]: Oh, I can understand that part now.

Then my opinion on this is

In the `iPadOS CinematicScrollView.OverlayView`, I think that normally work if the modifier only be applied to `FailureView`.

However, In other situations, it may be necessary to use the modifier of `FailureView`, which is contrary to the modifier of `ImageView`, so it would be good to provide the initializer in ImageView as you said.

However, there will be another problem because of the logic that should be handled in common with ImageView. (Placeholder you mentioned)

we need a better structure...
I think it would be good to think about it together.

Comment (LePips) [reply Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift:119]: It also does _not_ work if the modifier is applied to the `FailureView`.

Comment (LePips) [reply Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift:119]: Oh, it only works if the `alignment` is added to _both_ the failure view and the image view. For now, I kinda want to hold off on adding those modifiers due to the `ImageView` change I present which would these problems.

Comment (PangMo5) [reply Swiftfin/Views/ItemView/iPadOS/ScrollViews/iPadOSCinematicScrollView.swift:119]: Yes, I got it.
I will also think about `ImageView` refactoring.

**Comment by PangMo5** [comment]
image
The layout seems to be broken in the SeriesItemView when selected compact logo in iOS.

**Review by PangMo5 — DISMISSED** [review]
Due to this PR, Swiftfin's UI/UX has been greatly improved, and the development convenience has been increased and the structure of the project has been organized to some extent. 
Thank you for your amazing work! 😀

**Comment by LePips** [comment]
@PangMo5 Could you test this again with your media? I wasn't able to find any definitions that caused the framing to be smaller than the width, which would cause the `.background` to be smaller as expected. Thank you!

If you look at how the parallax and navbar offset views are created you can see why a `.background` is necessary for the content at the moment. This could be fixed later on by clipping the parallax header within the defined height that is already passed for the parallax movement computation.

**Comment by PangMo5** [comment]
Yeah, now it works as expected 👍

**Review by PangMo5 — APPROVED** [review]
:
