### PR TITLE
Modify External Subtitle URL Logic

### LINKED ISSUE #417: External subtitles are not displayed
### Describe the bug

All external subtitles are not displayed.

No matter the format of external subtitles is srt or ass can not be displayed.

Embedded subtitles can be displayed.

The video formats tested are all mkv.

### Application version

1.0.0(74)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 Pro

### OS version

IOS 15.4.1

### Jellyfin server version

10.8.0(docker nyanmisaka/jellyfin)

### PR DESCRIPTION
**Pull request by PangMo5**
Modify with reference to https://github.com/jellyfin/Swiftfin/issues/417#issuecomment-1173009298
Checked work normally in 10.7.7 and 10.8.1 (ass, srt)

### CODE REVIEW

File: Shared/Extensions/JellyfinAPIExtensions/MediaStreamExtension.swift [hunk 1]
```diff
@@ -10,12 +10,8 @@ import Foundation
...
 
 extension MediaStream {
-
 	func externalURL(base: String) -> URL? {
 		guard let deliveryURL = deliveryUrl else { return nil }
-		var baseComponents = URLComponents(string: base)
-		baseComponents?.path += deliveryURL
-
-		return baseComponents?.url
+		return URL(string: base + deliveryURL)
```
Comment (LePips) [inline Shared/Extensions/JellyfinAPIExtensions/MediaStreamExtension.swift:15]: Great find! However, we are not guaranteed that the base url does not end in a trailing `/`, and just simply appending it would break it. A check should be made first whether `base` ends in a trailing slash, removing it from the end of`base` or the first slash from `deliveryURL`, and then creating the URL.

**Review by LePips — CHANGES_REQUESTED** [review]

**Review by LePips — APPROVED** [review]
However, please do not close #417 as we need to address ShadowGhost's latest comment in that issue about the track re-ordering. I experienced this on my own media where the external subtitle track and the list of available subtitle tracks on `vlcMediaPlayer` don't match. This throws the player into an infinite loop at `didSelectSubtitleStream(...)` since I check that the correct subtitle track has been selected almost every second. We could possibly remove the that check, however the track re-ordering still needs to be addressed.

**Comment by PangMo5** [comment]
ok, I see.
